use crate::i18n::Language;

#[derive(Clone, Copy)]
pub enum Key {
    Positions,
    CurrentOrders,
    OrderHistory,
    Fills,
    PositionHistory,
    Bots,
    Assets,
    CurrentSymbol,
    NoAccount,
    Waiting,
    Empty,
    ConnectionRetry,
    ClockMismatch,
    RefreshDelayed,
    AccountDelayed,
    Symbol,
    Side,
    Size,
    Price,
    Entry,
    Mark,
    ValueUsd,
    CurrentPnl,
    Actions,
    Close,
    Reverse,
    CloseConfirm,
    ReverseConfirm,
    CloseExplain,
    ReverseExplain,
    MarketWarning,
    StrategyWarning,
    AccountChanged,
    Confirm,
    Cancel,
    State,
    Reason,
    Filled,
    Time,
    OrderId,
    FillId,
    ReduceOnly,
    Asset,
    Equity,
    Available,
    OrderHistoryScope,
    FillsScope,
    PositionHistoryScope,
    AssetsScope,
}

pub fn text(language: Language, key: Key) -> &'static str {
    let pair = match key {
        Key::Positions => ("持仓", "Positions"),
        Key::CurrentOrders => ("当前委托", "Open orders"),
        Key::OrderHistory => ("历史委托", "Order history"),
        Key::Fills => ("历史成交", "Trade history"),
        Key::PositionHistory => ("仓位历史", "Position history"),
        Key::Bots => ("交易机器人", "Trading bots"),
        Key::Assets => ("资产", "Assets"),
        Key::CurrentSymbol => ("仅当前交易对", "Current symbol"),
        Key::NoAccount => ("未选择交易帐户", "No trading account"),
        Key::Waiting => ("等待账户签名数据", "Waiting for signed account data"),
        Key::Empty => (
            "暂无已投影记录（不代表账户已确认空仓）",
            "No projected records; account emptiness is not confirmed",
        ),
        Key::ConnectionRetry => (
            "账户连接异常，正在重试；旧数据仅供查看",
            "Account connection failed; retrying. Previous data is read only.",
        ),
        Key::ClockMismatch => (
            "账户数据时间异常，请检查电脑时间",
            "Account data time mismatch; check the computer clock.",
        ),
        Key::RefreshDelayed => (
            "尚未收到最新账户数据，正在重试；旧数据仅供查看",
            "Account refresh delayed; retrying. Previous data is read only.",
        ),
        Key::AccountDelayed => (
            "服务端账户数据暂未更新；旧数据仅供查看",
            "Server account data has not updated; previous data is read only.",
        ),
        Key::Symbol => ("交易对", "Symbol"),
        Key::Side => ("方向", "Side"),
        Key::Size => ("数量", "Size"),
        Key::Price => ("价格", "Price"),
        Key::Entry => ("开仓均价", "Entry"),
        Key::Mark => ("标记价格", "Mark"),
        Key::ValueUsd => ("价值 (USD)", "Value (USD)"),
        Key::CurrentPnl => ("当前 PnL", "Current PnL"),
        Key::Actions => ("操作", "Actions"),
        Key::Close => ("平仓", "Close"),
        Key::Reverse => ("反开", "Reverse"),
        Key::CloseConfirm => ("市价平仓", "Market close"),
        Key::ReverseConfirm => ("市价反开", "Market reverse"),
        Key::CloseExplain => (
            "按该行数量市价平仓；仓位已减少时只平剩余数量。",
            "Close this row at market, capped to the remaining position.",
        ),
        Key::ReverseExplain => (
            "先平掉该行仓位，确认平仓后按实际平掉的数量反向开仓。已有反向仓位会被追加。",
            "Close this leg first, then open the opposite leg for the confirmed closed quantity. Existing opposite exposure will increase.",
        ),
        Key::MarketWarning => (
            "市价成交可能滑点；反开是两笔交易，不能保证同时成功。",
            "Market orders may slip. Reversal uses two orders; both are not guaranteed to succeed.",
        ),
        Key::StrategyWarning => (
            "不会撤销挂单或停止网格；运行中的策略可能再次建仓。",
            "Open orders and running strategies are unchanged; a strategy may reopen exposure.",
        ),
        Key::AccountChanged => (
            "执行账户已切换，请取消并重新选择持仓。",
            "Execution account changed. Cancel and select the position again.",
        ),
        Key::Confirm => ("确认提交", "Confirm"),
        Key::Cancel => ("取消", "Cancel"),
        Key::State => ("状态", "State"),
        Key::Reason => ("异常原因", "Failure reason"),
        Key::Filled => ("已成交", "Filled"),
        Key::Time => ("更新时间", "Updated"),
        Key::OrderId => ("委托号", "Order ID"),
        Key::FillId => ("成交号", "Fill ID"),
        Key::ReduceOnly => ("只减仓", "Reduce only"),
        Key::Asset => ("资产", "Asset"),
        Key::Equity => ("权益", "Equity"),
        Key::Available => ("可用保证金", "Available margin"),
        Key::OrderHistoryScope => (
            "仅显示 Venue 命令记录；已提交或已接受不代表已成交。外部历史委托不在此列表。",
            "Venue command records only; submitted or accepted does not mean filled. External order history is not included.",
        ),
        Key::FillsScope => (
            "仅显示网关账户流及签名补查已投影的最近成交，不代表完整账户历史。",
            "Shows only recent fills projected from the gateway stream and signed recovery.",
        ),
        Key::PositionHistoryScope => (
            "最近 500 条仓位变更，数量为 0 表示该腿已平；不包含绑定前完整历史或已实现盈亏。",
            "Last 500 observed position changes; zero quantity means that leg closed. Not full pre-binding history or realized PnL.",
        ),
        Key::AssetsScope => (
            "最近一次签名资产快照；USD 是统一账户计价，不等于 USDC 余额。资产不随仓位事件实时刷新。",
            "Latest signed asset snapshot. USD is portfolio valuation, not a USDC balance. Position events do not refresh balances.",
        ),
    };
    match language {
        Language::SimplifiedChinese => pair.0,
        Language::English => pair.1,
    }
}
