use crate::i18n::Language;

#[derive(Clone, Copy)]
pub enum Key {
    Positions,
    CurrentOrders,
    OrderHistory,
    Fills,
    PositionHistory,
    Bots,
    Assets,
    CurrentSymbol,
    NoAccount,
    Waiting,
    Empty,
    ConnectionRetry,
    ClockMismatch,
    RefreshDelayed,
    AccountDelayed,
    Symbol,
    Side,
    Size,
    Price,
    Entry,
    Mark,
    ValueUsd,
    CurrentPnl,
    Actions,
    Close,
    Reverse,
    CloseConfirm,
    ReverseConfirm,
    CloseExplain,
    ReverseExplain,
    MarketWarning,
    StrategyWarning,
    AccountChanged,
    Cancel,
    State,
    Reason,
    Filled,
    Time,
    OrderId,
    FillId,
    ReduceOnly,
    Asset,
    Equity,
    Available,
    AssetsScope,
}

pub fn text(language: Language, key: Key) -> &'static str {
    let pair = match key {
        Key::Positions => ("持仓", "Positions"),
        Key::CurrentOrders => ("当前委托", "Open orders"),
        Key::OrderHistory => ("历史委托", "Order history"),
        Key::Fills => ("历史成交", "Trade history"),
        Key::PositionHistory => ("仓位历史", "Position history"),
        Key::Bots => ("交易机器人", "Trading bots"),
        Key::Assets => ("资产", "Assets"),
        Key::CurrentSymbol => ("仅当前交易对", "Current symbol"),
        Key::NoAccount => ("未选择交易帐户", "No trading account"),
        Key::Waiting => ("等待账户签名数据", "Waiting for signed account data"),
        Key::Empty => (
            "暂无已投影记录（不代表账户已确认空仓）",
            "No projected records; account emptiness is not confirmed",
        ),
        Key::ConnectionRetry => (
            "账户连接异常，正在重试；旧数据仅供查看",
            "Account connection failed; retrying. Previous data is read only.",
        ),
        Key::ClockMismatch => (
            "账户数据时间异常，请检查电脑时间",
            "Account data time mismatch; check the computer clock.",
        ),
        Key::RefreshDelayed => (
            "尚未收到最新账户数据，正在重试；旧数据仅供查看",
            "Account refresh delayed; retrying. Previous data is read only.",
        ),
        Key::AccountDelayed => (
            "服务端账户数据暂未更新；旧数据仅供查看",
            "Server account data has not updated; previous data is read only.",
        ),
        Key::Symbol => ("交易对", "Symbol"),
        Key::Side => ("方向", "Side"),
        Key::Size => ("数量", "Size"),
        Key::Price => ("价格", "Price"),
        Key::Entry => ("开仓均价", "Entry"),
        Key::Mark => ("标记价格", "Mark"),
        Key::ValueUsd => ("价值 (USD)", "Value (USD)"),
        Key::CurrentPnl => ("当前 PnL", "Current PnL"),
        Key::Actions => ("操作", "Actions"),
        Key::Close => ("平仓", "Close"),
        Key::Reverse => ("反开", "Reverse"),
        Key::CloseConfirm => ("市价平仓", "Market close"),
        Key::ReverseConfirm => ("市价反开", "Market reverse"),
        Key::CloseExplain => (
            "市价平仓，最多平掉当前剩余数量。",
            "Close at market, up to the remaining quantity.",
        ),
        Key::ReverseExplain => (
            "先平仓，再按实平数量反向开仓。已有反向仓位会追加，开仓可能失败。",
            "Close first, then reverse the filled quantity. Adds to an existing opposite position; reopening may fail.",
        ),
        Key::MarketWarning => ("成交价可能滑点。", "Execution price may slip."),
        Key::StrategyWarning => (
            "挂单和策略继续运行，可能再次建仓。",
            "Orders and strategies remain active and may reopen positions.",
        ),
        Key::AccountChanged => (
            "账户已切换，请重新选择持仓。",
            "Account changed. Select the position again.",
        ),
        Key::Cancel => ("取消", "Cancel"),
        Key::State => ("状态", "State"),
        Key::Reason => ("异常原因", "Failure reason"),
        Key::Filled => ("已成交", "Filled"),
        Key::Time => ("更新时间", "Updated"),
        Key::OrderId => ("委托号", "Order ID"),
        Key::FillId => ("成交号", "Fill ID"),
        Key::ReduceOnly => ("只减仓", "Reduce only"),
        Key::Asset => ("资产", "Asset"),
        Key::Equity => ("权益", "Equity"),
        Key::Available => ("可用保证金", "Available margin"),
        Key::AssetsScope => (
            "最近一次签名资产快照；USD 是统一账户计价，不等于 USDC 余额。资产不随仓位事件实时刷新。",
            "Latest signed asset snapshot. USD is portfolio valuation, not a USDC balance. Position events do not refresh balances.",
        ),
    };
    match language {
        Language::SimplifiedChinese => pair.0,
        Language::English => pair.1,
    }
}
