use crate::i18n::Language;

#[derive(Clone, Copy)]
pub enum Key {
    Positions,
    CurrentOrders,
    OrderHistory,
    Fills,
    PositionHistory,
    Bots,
    Assets,
    CurrentSymbol,
    NoAccount,
    Waiting,
    Empty,
    Stale,
    Symbol,
    Side,
    Size,
    Price,
    Entry,
    Mark,
    CurrentPnl,
    State,
    Reason,
    Filled,
    Time,
    OrderId,
    FillId,
    ReduceOnly,
    Signed,
    Asset,
    Equity,
    Available,
    CurrentSource,
    OrderHistoryScope,
    FillsScope,
    PositionHistoryScope,
    AssetsScope,
}

pub fn text(language: Language, key: Key) -> &'static str {
    let pair = match key {
        Key::Positions => ("持仓", "Positions"),
        Key::CurrentOrders => ("当前委托", "Open orders"),
        Key::OrderHistory => ("历史委托", "Order history"),
        Key::Fills => ("历史成交", "Trade history"),
        Key::PositionHistory => ("仓位历史", "Position history"),
        Key::Bots => ("交易机器人", "Trading bots"),
        Key::Assets => ("资产", "Assets"),
        Key::CurrentSymbol => ("仅当前交易对", "Current symbol"),
        Key::NoAccount => ("未选择交易帐户", "No trading account"),
        Key::Waiting => ("等待账户签名数据", "Waiting for signed account data"),
        Key::Empty => (
            "暂无已投影记录（不代表账户已确认空仓）",
            "No projected records; account emptiness is not confirmed",
        ),
        Key::Stale => (
            "数据过期 / 连接异常，仅供查看",
            "Stale / disconnected — read only",
        ),
        Key::Symbol => ("交易对", "Symbol"),
        Key::Side => ("方向", "Side"),
        Key::Size => ("数量", "Size"),
        Key::Price => ("价格", "Price"),
        Key::Entry => ("开仓均价", "Entry"),
        Key::Mark => ("标记价格", "Mark"),
        Key::CurrentPnl => ("当前 PnL", "Current PnL"),
        Key::State => ("状态", "State"),
        Key::Reason => ("异常原因", "Failure reason"),
        Key::Filled => ("已成交", "Filled"),
        Key::Time => ("更新时间", "Updated"),
        Key::OrderId => ("委托号", "Order ID"),
        Key::FillId => ("成交号", "Fill ID"),
        Key::ReduceOnly => ("只减仓", "Reduce only"),
        Key::Signed => ("签名投影", "Signed projection"),
        Key::Asset => ("资产", "Asset"),
        Key::Equity => ("权益", "Equity"),
        Key::Available => ("可用保证金", "Available margin"),
        Key::CurrentSource => (
            "由 Binance Executor 统一提供签名账户数据；连接中断后旧值仅供查看。",
            "Signed account data from Binance Executor; stale values are read only.",
        ),
        Key::OrderHistoryScope => (
            "仅显示 Venue 命令记录；已提交或已接受不代表已成交。外部历史委托不在此列表。",
            "Venue command records only; submitted or accepted does not mean filled. External order history is not included.",
        ),
        Key::FillsScope => (
            "仅显示网关账户流及签名补查已投影的最近成交，不代表完整账户历史。",
            "Shows only recent fills projected from the gateway stream and signed recovery.",
        ),
        Key::PositionHistoryScope => (
            "最近 500 条仓位变更，数量为 0 表示该腿已平；不包含绑定前完整历史或已实现盈亏。",
            "Last 500 observed position changes; zero quantity means that leg closed. Not full pre-binding history or realized PnL.",
        ),
        Key::AssetsScope => (
            "最近一次签名资产快照；USD 是统一账户计价，不等于 USDC 余额。资产不随仓位事件实时刷新。",
            "Latest signed asset snapshot. USD is portfolio valuation, not a USDC balance. Position events do not refresh balances.",
        ),
    };
    match language {
        Language::SimplifiedChinese => pair.0,
        Language::English => pair.1,
    }
}
