import type { Metadata } from "next";
import Link from "next/link";
import { CopyIp } from "./copy-ip";
import "./guide.css";

export const metadata: Metadata = { title: "KOL 使用指南 · Venue", description: "从币安 API 设置到邀请用户，按步骤完成带单配置与问题排查。" };
const steps = [["prepare", "准备币安账户"], ["api", "创建与验证 API"], ["source", "指定带单账户"], ["invite", "邀请与配置跟单"], ["check", "确认正在跟单"], ["pause", "暂停与退出"], ["troubleshooting", "常见问题"]];
const ip = "45.77.253.180";
export default function KolGuide() {
  return <main className="kol-guide" id="top">
    <header className="guide-header"><Link href="/">← 返回后台</Link><span>VENUE · 使用帮助</span><a href="#troubleshooting">遇到问题？</a></header>
    <section className="guide-hero"><p className="guide-kicker">KOL 操作指南</p><h1>从准备账户，到开始带单</h1><p>按下面的顺序完成设置。每一步都给出操作位置和完成标志，首次使用可从头阅读，之后可直接跳到需要的部分。</p><div className="guide-flow" aria-label="配置流程"><span>币安 API</span><b aria-hidden="true">→</b><span>唯一带单账户</span><b aria-hidden="true">→</b><span>邀请用户</span><b aria-hidden="true">→</b><span>启动与确认</span></div><p className="guide-small">适用于平台手工创建的 KOL 账户。跟单用户通过邀请码注册，不会自动成为 KOL。</p></section>
    <div className="guide-layout"><nav className="guide-nav" aria-label="指南目录"><strong>本页目录</strong>{steps.map(([id, title], n) => <a key={id} href={`#${id}`}><span>{String(n + 1).padStart(2, "0")}</span>{title}</a>)}<Link href="/">回后台继续设置 ↗</Link></nav>
    <article className="guide-content">
      <section id="prepare"><p className="guide-kicker">01 · 开始之前</p><h2>先确认账户类型</h2><p>KOL 与跟单账户都必须使用<strong>币安统一账户（Portfolio Margin）</strong>，并开启 <strong>U 本位合约双向持仓</strong>。普通合约账户或单向持仓不能通过当前系统验证。</p><ul><li>准备币安登录信息、绑定邮箱和身份验证器，用于币安安全验证。</li><li>确认自己有权使用这组 API。跟单用户可自行绑定，不必把密钥发给 KOL。</li><li>新跟单账户启用前需无已有仓位、无挂单，并通过系统检查。不要为了通过检查而盲目平仓，先处理原有交易。</li></ul><p className="guide-note">带单与跟单各自成交，成交价、成交时间和收益可能不同。手续费、资金费与滑点按交易所实际情况发生，系统不保证零成本或本金无损。</p></section>
      <section id="api"><p className="guide-kicker">02 · API 设置</p><h2>创建 API，并确认验证通过</h2><details open><summary>电脑网页操作</summary><ol><li>登录币安，进入<strong>账户 → API 管理 → 创建 API</strong>，选择<strong>系统生成</strong>。</li><li>填写方便识别的名称，例如“Venue 带单”，按币安提示完成邮箱和身份验证器验证。</li><li>取得两项内容：<strong>API密钥</strong>和<strong>密钥</strong>。它们不同，填写时不要对调；不要把内容放进截图或聊天消息。</li></ol><figure><a href="/help/kol/binance-create-api.png" target="_blank" rel="noreferrer"><img src="/help/kol/binance-create-api.png" alt="币安网页：API 管理中点击创建 API，选择系统生成，再点下一步" width="2214" height="1410" loading="lazy" /></a><figcaption>图示：系统生成入口。点击图片可放大；币安界面可能随版本调整。</figcaption></figure></details>
      <details><summary>币安 App 操作</summary><p>在币安 App 进入<strong>更多服务 → 其他 → API 管理</strong>，创建系统生成的 API，完成安全验证。若找不到入口，可在服务中搜索“API 管理”或改用电脑网页。</p><figure><a href="/help/kol/binance-mobile-api.png" target="_blank" rel="noreferrer"><img src="/help/kol/binance-mobile-api.png" alt="币安 App：更多服务中打开其他分类，选择 API 管理" width="1650" height="1302" loading="lazy" /></a><figcaption>图示：App 的 API 管理入口。</figcaption></figure></details>
      <h3>设置访问权限</h3><ol><li>打开这组 API 的<strong>编辑权限</strong>。</li><li>在 IP 访问限制中选择<strong>只访问受信任的 IP</strong>，添加本站生产服务 IP，点击确认。</li><li>启用<strong>允许读取</strong>与所需的 <strong>U 本位合约交易权限</strong>，关闭提现权限。最后点击<strong>保存</strong>并完成安全验证。</li></ol><CopyIp value={ip} /><p className="guide-small">这是 clawdbotweb.site 当前生产服务的出口 IP，不是你的电脑 IP。自建部署请向对应管理员确认出口 IP。</p><p>若刚升级为统一账户，请重新检查这组 API 的合约权限。币安说明升级可能移除既有 API 的合约权限，不能只看升级前的设置。<a href="https://www.binance.com/en-KZ/support/faq/detail/ccf04078d7774d479f11ae15c4f56081" target="_blank" rel="noreferrer">查看币安说明 ↗</a></p>
      <h3>回 Venue 绑定并验证</h3><ol><li>打开后台<strong>交易账户 → 添加交易账户</strong>，填写名称和两项密钥，然后点击<strong>绑定交易账户</strong>。</li><li>在账户行点击<strong>验证权限</strong>。</li><li>确认出现<strong>验证通过</strong>，再进行下一步。出现失败提示时，先按提示修正币安设置并重新验证。</li></ol><div className="guide-mapping" aria-label="字段对应示意"><div><span>币安</span><strong>API密钥</strong><small>复制 API Key</small></div><b aria-hidden="true">→</b><div><span>Venue</span><strong>API密钥</strong><small>粘贴到同名字段</small></div><div><span>币安</span><strong>密钥</strong><small>复制 Secret Key</small></div><b aria-hidden="true">→</b><div><span>Venue</span><strong>密钥</strong><small>粘贴到同名字段</small></div></div><p className="guide-note">“绑定成功”只表示已保存；“请求已处理”也不等于验证成功。必须以账户行的<strong>验证结果</strong>为准。</p></section>
      <section id="source"><p className="guide-kicker">03 · 带单账户</p><h2>指定唯一的带单账户</h2><ol><li>找到<strong>带单账户（只能选择一个）</strong>。</li><li>从下拉框选择刚刚验证通过的账户，点击<strong>保存带单账户</strong>。</li><li>核对<strong>当前带单账户</strong>显示的名称。尚未指定时，不应把任意绑定账户当作带单源。</li></ol><div className="guide-done"><strong>完成标志</strong><p>已显示正确的带单账户。初始带单权限自动开通，无需再申请审批；保存账户不会自动启动带单。</p></div><p>可以保存多组本人 API，但只有一个账户作为带单源。已有带单机器人或跟单关系时，源账户会锁定，不能直接切换，以免改变历史订单归属。</p><h3>创建并启动带单</h3><p>在后台的带单机器人区域点击“创建带单机器人”，核对所选账户，勾选启动确认，再点击“启动带单”。当前 Web 会以首次指定账户时的验证权益初始化 KOL 策略资金，用于定比计算，无需在此另填。需要看到<strong>运行中</strong>，仅创建配置或保存账户还没有开始同步。</p></section>
      <section id="invite"><p className="guide-kicker">04 · 跟单用户</p><h2>邀请用户，或管理已获委托的账户</h2><h3>用户自己绑定 API</h3><ol><li>KOL 在<strong>邀请跟单用户</strong>区域点击<strong>生成邀请码</strong>，或输入自己的代码后点击<strong>使用自定义邀请码</strong>。</li><li>把邀请链接或邀请码发给用户。邀请码为 6–64 位字母、数字、短横线或下划线，区分大小写；不同 KOL 不能使用重复代码。</li><li>用户通过链接注册，或在注册页填写邀请码。注册后归属于该 KOL，不能随意更换归属。</li><li>用户添加自己的跟单账户，选择定比或定额，完成 API 验证。系统按保存的授权申请启用，待账户检查通过后开始跟单。</li></ol><h3>KOL 托管已获委托的账户</h3><p>在<strong>托管跟单账户</strong>区域添加账户，为每个账户分别填写 API 和跟单方式。只管理已得到所有者委托的账户；用户自行绑定的密钥不会展示给 KOL。</p>
      <div id="sizing"><h3>定比与定额怎么选</h3><div className="guide-compare"><div><h4>定比跟单</h4><p>跟单数量随带单订单大小变化，按账户验证权益、KOL 策略资金和跟单倍数计算，默认 1 倍。</p><p>示例：跟单权益 20 U、策略资金 100 U、1 倍时，计划数量约为源单的 20%，之后再按交易所规则取整。</p></div><div><h4>定额跟单</h4><p>每笔按固定的<strong>报价币名义金额</strong>计算，不是固定保证金，也不是杠杆倍数。</p><p>示例：填 10 U，表示每笔计划订单价值约 10 U；实际数量仍受最小下单量和精度影响。</p></div></div><p>无需另填总跟单金额或项目止损。新跟单订单不受软件单笔或总名义金额上限拦截，币安仍检查保证金与账户交易规则。定比使用验证时的权益快照，后续转入资金不会自动改变该比例。</p><p>小额开仓可能补足至交易所最低下单额，所以实际金额可能高于计划值。平仓只按可减持仓裁剪。跟单中设置只读，需要先暂停并完成撤单对账后再修改。</p></div></section>
      <section id="check"><p className="guide-kicker">05 · 运行确认</p><h2>用账户状态和实际订单确认</h2><ol><li>确认 KOL 带单处于<strong>运行中</strong>，跟单账户显示<strong>跟单中</strong>，没有待处理提示。</li><li>系统同步启用后的新限价单、市价单与受支持的止损单，不追补启用前的仓位，也不自动补下此前已拒绝的订单。</li><li>到跟单账户查看同步订单及币安订单、成交和持仓。<strong>已挂单不等于已成交</strong>，主账户成交也不保证子账户同时成交。</li></ol><div className="guide-status"><p><strong>待执行 / 已挂单</strong><span>订单尚在处理或等待成交。</span></p><p><strong>未下单 / 需要处理</strong><span>查看原因，检查权限、账户模式、保证金及交易所规则。</span></p><p><strong>正在撤销同步挂单</strong><span>等待原订单确认结束，勿用重复开关或重复提交强行推进。</span></p></div></section>
      <section id="pause"><p className="guide-kicker">06 · 暂停与退出</p><h2>先暂停，再确认订单与持仓</h2><ol><li>在对应跟单设置中发起暂停；KOL 停止带单时，按带单区域的停止操作处理。</li><li>等待程序撤销未成交的子单，并确认页面不再显示撤单中或需要处理。</li><li>到币安核对剩余订单和持仓。<strong>暂停不会自动平掉已有持仓</strong>，持仓需要账户所有者自行管理。</li><li>如要删除绑定，按页面提示完成。不要在正常撤单和查单尚未结束前提前撤掉 API 权限。</li></ol><p className="guide-note">转走保证金不能代替暂停，已有持仓仍可能面临风险。如发现密钥泄露或异常交易，应优先在币安撤销该 API，并直接在币安检查和处理订单、持仓。</p></section>
      <section id="troubleshooting"><p className="guide-kicker">07 · 常见问题</p><h2>卡在哪一步，就从这里排查</h2>
      <details><summary>验证显示 permission_denied 或“币安 API 访问被拒绝”</summary><p>依次检查 IP 白名单是否包含 {ip}、是否点击确认并保存、读取与合约交易权限是否正确、账户是否为统一账户。刚升级账户后要重新检查 API 权限。这个状态不能用于判断是哪一项出错，修改后需要重新验证。</p></details>
      <details><summary>密钥无效、账户模式不符或暂时无法连接</summary><p>密钥无效：重新从币安复制成对的 API密钥与密钥，检查是否对调或多了空格。模式不符：确认 Portfolio Margin 与 U 本位双向持仓。网络不可用：稍后重试验证，不必重复绑定同一组 API。</p></details>
      <details><summary>下拉框里没有账户，或邀请码按钮不能点击</summary><p>先让账户验证通过，再保存唯一带单账户。KOL 尚未启用时不能生成邀请码；已创建的 KOL 完成验证与指定后会自动获得初始权限。若管理员曾明确撤权，需要联系管理员确认。</p></details>
      <details><summary>主账户有订单，为什么没有跟单？</summary><p>确认是启用后的新订单、带单处于运行中、跟单账户处于跟单中。再查看是否有未知订单待对账、权限或账户模式变化、保证金不足、价格偏离或交易所数量限制。单看现有仓位金额，不能确定新订单是否满足所有条件。</p></details>
      <details><summary>定比账户追加资金后，数量为什么没变化？</summary><p>当前比例使用验证时的权益快照，不会随转账或浮盈实时更新。需要调整时，先暂停并完成撤单对账，再重新验证账户、保存跟单设置并检查新的参数。</p></details>
      <details><summary>停止跟单后还有持仓，可以直接删 API 吗？</summary><p>暂停与删除绑定不等于平仓。先核对币安上的挂单、已有持仓和撤单状态。正常退出时，等待必要的查单和撤单完成再删除；如密钥已泄露，直接在币安撤销并自行管理持仓。</p></details>
      </section>
      <footer className="guide-footer"><p>图文素材来自 <a href="https://github.com/zhuco/Venue/pull/2" target="_blank" rel="noreferrer">ouyang6559（qile）贡献的 PR #2</a>；网页按现行 Venue 流程校订。币安入口图仅作导航参考，具体按钮以当前币安页面为准。</p><p><a href="https://www.binance.com/en/support/faq/detail/360002502072" target="_blank" rel="noreferrer">币安官方 API 创建说明 ↗</a> · <a href="#top">回到顶部 ↑</a></p><Link href="/">返回后台继续设置 →</Link></footer>
    </article></div>
  </main>;
}
