[build]
target-dir = "G:/Build/Venue/main"

[profile.dev]
debug = "line-tables-only"

[profile.dev.package."*"]
debug = false

[profile.test]
debug = "line-tables-only"

[profile.test.package."*"]
debug = false
