use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};

use crate::domain::{OrderPurpose, OrderSide, PositionSide, Price, Symbol};

/// Stable identity for one mutation attempt. It is never generated by an exchange adapter.
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize, Deserialize)]
#[serde(transparent)]
pub struct CommandId(String);

impl CommandId {
    pub fn new(raw: impl Into<String>) -> Result<Self, CommandError> {
        let value = raw.into();
        if valid_identifier(&value) {
            Ok(Self(value))
        } else {
            Err(CommandError::Identifier)
        }
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// Immutable ownership scope required before an order can acquire exchange side effects.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct OrderOwner {
    pub strategy_instance_id: String,
    pub run_id: String,
    pub exchange: String,
    pub account: String,
    pub symbol: Symbol,
    pub purpose: OrderPurpose,
}

impl OrderOwner {
    pub fn validate(&self) -> Result<(), CommandError> {
        for value in [
            &self.strategy_instance_id,
            &self.run_id,
            &self.exchange,
            &self.account,
        ] {
            if !valid_identifier(value) {
                return Err(CommandError::Owner);
            }
        }
        Ok(())
    }
}

/// A priced limit instruction.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct OrderCommand {
    pub command_id: CommandId,
    pub client_order_id: CommandId,
    pub owner: OrderOwner,
    pub side: OrderSide,
    /// PAPI UM Hedge Mode requires the side of the position being opened or reduced.
    pub position_side: PositionSide,
    #[serde(with = "rust_decimal::serde::str")]
    pub quantity: Decimal,
    pub limit_price: Price,
    pub reduce_only: bool,
}

/// An exposure-increasing market instruction. It is intentionally separate from `OrderCommand`:
/// a market order has no limit price and its explicit `reduce_only=false` invariant is checked
/// before any exchange adapter call. Execution must supply a current-price and notional guard.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct MarketOrderCommand {
    pub command_id: CommandId,
    pub client_order_id: CommandId,
    pub owner: OrderOwner,
    /// PAPI UM Hedge Mode requires the concrete position side to open.
    pub position_side: PositionSide,
    pub side: OrderSide,
    #[serde(with = "rust_decimal::serde::str")]
    pub quantity: Decimal,
    pub reduce_only: bool,
}

/// A generation-fenced market reduction created only by one persisted exposure-profit episode.
/// It has no `reduce_only` boolean: reducing the declared Hedge leg is its only valid meaning.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct MarketReduceCommand {
    pub command_id: CommandId,
    pub client_order_id: CommandId,
    pub owner: OrderOwner,
    pub position_side: PositionSide,
    pub side: OrderSide,
    #[serde(with = "rust_decimal::serde::str")]
    pub quantity: Decimal,
    pub risk_episode_id: CommandId,
    pub position_generation: u64,
}

/// A Binance hedge-side protection instruction. It closes the entire declared LONG or SHORT
/// position at market once the mark-price trigger is reached, so it deliberately has no quantity
/// or limit-price field that could turn it into an entry or partial reduction.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct StopMarketCloseAllCommand {
    pub command_id: CommandId,
    /// PAPI conditional orders use a strategy identity, not an ordinary client order ID.
    pub client_strategy_id: CommandId,
    pub owner: OrderOwner,
    pub side: OrderSide,
    pub position_side: PositionSide,
    pub stop_price: Price,
    pub position_generation: u64,
}

/// A current PAPI UM Algo STOP_MARKET or TAKE_PROFIT_MARKET instruction. The exact wire type is
/// selected by the immutable owner purpose (`Protection` or `TakeProfit`). Portfolio Margin Hedge Mode forbids the
/// wire-level `reduceOnly` flag, so safety is expressed by freezing the exact authoritative
/// hedge-leg quantity and its private-position generation in the durable command.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct StopMarketFullPositionCommand {
    pub command_id: CommandId,
    pub client_algo_id: CommandId,
    pub owner: OrderOwner,
    pub side: OrderSide,
    pub position_side: PositionSide,
    #[serde(with = "rust_decimal::serde::str")]
    pub quantity: Decimal,
    pub trigger_price: Price,
    pub position_generation: u64,
}

/// Cancellation is scoped to one owner and one prior client order identity; symbol-wide cancels
/// are intentionally not represented.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct CancelCommand {
    pub command_id: CommandId,
    pub owner: OrderOwner,
    pub target_client_order_id: CommandId,
}

impl CancelCommand {
    pub fn validate(&self) -> Result<(), CommandError> {
        self.owner.validate()
    }
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case", tag = "kind", content = "payload")]
pub enum ExecutionCommand {
    PlaceLimit(OrderCommand),
    PlaceMarket(MarketOrderCommand),
    MarketReduce(MarketReduceCommand),
    StopMarketCloseAll(StopMarketCloseAllCommand),
    StopMarketFullPosition(StopMarketFullPositionCommand),
    Cancel(CancelCommand),
}

/// Native order families have separate idempotency and exact-readback endpoints on PAPI UM.
#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum NativeOrderFamily {
    UmOrder,
    UmConditional,
    UmAlgo,
}

impl ExecutionCommand {
    pub fn command_id(&self) -> &CommandId {
        match self {
            Self::PlaceLimit(command) => &command.command_id,
            Self::PlaceMarket(command) => &command.command_id,
            Self::MarketReduce(command) => &command.command_id,
            Self::StopMarketCloseAll(command) => &command.command_id,
            Self::StopMarketFullPosition(command) => &command.command_id,
            Self::Cancel(command) => &command.command_id,
        }
    }

    pub fn native_client_id(&self) -> Option<&CommandId> {
        match self {
            Self::PlaceLimit(command) => Some(&command.client_order_id),
            Self::PlaceMarket(command) => Some(&command.client_order_id),
            Self::MarketReduce(command) => Some(&command.client_order_id),
            Self::StopMarketCloseAll(command) => Some(&command.client_strategy_id),
            Self::StopMarketFullPosition(command) => Some(&command.client_algo_id),
            Self::Cancel(_) => None,
        }
    }

    pub const fn native_order_family(&self) -> Option<NativeOrderFamily> {
        match self {
            Self::PlaceLimit(_) | Self::PlaceMarket(_) | Self::MarketReduce(_) => {
                Some(NativeOrderFamily::UmOrder)
            }
            Self::StopMarketCloseAll(_) => Some(NativeOrderFamily::UmConditional),
            Self::StopMarketFullPosition(_) => Some(NativeOrderFamily::UmAlgo),
            Self::Cancel(_) => None,
        }
    }

    pub fn validate(&self) -> Result<(), CommandError> {
        match self {
            Self::PlaceLimit(command) => command.validate(),
            Self::PlaceMarket(command) => command.validate(),
            Self::MarketReduce(command) => command.validate(),
            Self::StopMarketCloseAll(command) => command.validate(),
            Self::StopMarketFullPosition(command) => command.validate(),
            Self::Cancel(command) => command.validate(),
        }
    }

    pub fn owner(&self) -> Option<&OrderOwner> {
        match self {
            Self::PlaceLimit(command) => Some(&command.owner),
            Self::PlaceMarket(command) => Some(&command.owner),
            Self::MarketReduce(command) => Some(&command.owner),
            Self::StopMarketCloseAll(command) => Some(&command.owner),
            Self::StopMarketFullPosition(command) => Some(&command.owner),
            Self::Cancel(_) => None,
        }
    }

    /// Exact owner for every physical mutation, including cancellation. `owner()` preserves its
    /// historical meaning for commands that create an exchange order; account-level scheduling
    /// must use this method so a cancel cannot bypass ownership checks.
    pub const fn mutation_owner(&self) -> &OrderOwner {
        match self {
            Self::PlaceLimit(command) => &command.owner,
            Self::PlaceMarket(command) => &command.owner,
            Self::MarketReduce(command) => &command.owner,
            Self::StopMarketCloseAll(command) => &command.owner,
            Self::StopMarketFullPosition(command) => &command.owner,
            Self::Cancel(command) => &command.owner,
        }
    }
}

impl StopMarketCloseAllCommand {
    pub fn validate(&self) -> Result<(), CommandError> {
        self.owner.validate()?;
        if self.owner.purpose != OrderPurpose::Protection {
            return Err(CommandError::ProtectionPurpose);
        }
        if !matches!(self.position_side, PositionSide::Long | PositionSide::Short) {
            return Err(CommandError::ProtectionPositionSide);
        }
        let expected_side = match self.position_side {
            PositionSide::Long => OrderSide::Sell,
            PositionSide::Short => OrderSide::Buy,
            PositionSide::Net => return Err(CommandError::ProtectionPositionSide),
        };
        if self.side != expected_side {
            return Err(CommandError::ProtectionSide);
        }
        if self.position_generation == 0 {
            return Err(CommandError::PositionGeneration);
        }
        Ok(())
    }
}

impl StopMarketFullPositionCommand {
    pub fn validate(&self) -> Result<(), CommandError> {
        self.owner.validate()?;
        if !matches!(
            self.owner.purpose,
            OrderPurpose::Protection | OrderPurpose::TakeProfit
        ) {
            return Err(CommandError::ProtectionPurpose);
        }
        if !self.quantity.is_sign_positive() || self.quantity.is_zero() {
            return Err(CommandError::Quantity);
        }
        if !matches!(self.position_side, PositionSide::Long | PositionSide::Short) {
            return Err(CommandError::ProtectionPositionSide);
        }
        let expected_side = match self.position_side {
            PositionSide::Long => OrderSide::Sell,
            PositionSide::Short => OrderSide::Buy,
            PositionSide::Net => return Err(CommandError::ProtectionPositionSide),
        };
        if self.side != expected_side {
            return Err(CommandError::ProtectionSide);
        }
        if self.position_generation == 0 {
            return Err(CommandError::PositionGeneration);
        }
        Ok(())
    }
}

impl OrderCommand {
    pub fn validate(&self) -> Result<(), CommandError> {
        self.owner.validate()?;
        if self.owner.purpose == OrderPurpose::ExposureTakeProfit {
            return Err(CommandError::MarketReducePurpose);
        }
        if !self.quantity.is_sign_positive() || self.quantity.is_zero() {
            return Err(CommandError::Quantity);
        }
        let requires_reduce_only = matches!(
            self.owner.purpose,
            OrderPurpose::Protection | OrderPurpose::TakeProfit | OrderPurpose::Reduce
        );
        if self.reduce_only != requires_reduce_only {
            return Err(CommandError::ReduceOnly);
        }
        if !matches!(self.position_side, PositionSide::Long | PositionSide::Short) {
            return Err(CommandError::PositionSide);
        }
        let expected_side = match (self.owner.purpose, self.position_side) {
            (OrderPurpose::Entry, PositionSide::Long) => OrderSide::Buy,
            (OrderPurpose::Entry, PositionSide::Short) => OrderSide::Sell,
            (
                OrderPurpose::Protection | OrderPurpose::TakeProfit | OrderPurpose::Reduce,
                PositionSide::Long,
            ) => OrderSide::Sell,
            (
                OrderPurpose::Protection | OrderPurpose::TakeProfit | OrderPurpose::Reduce,
                PositionSide::Short,
            ) => OrderSide::Buy,
            (OrderPurpose::ExposureTakeProfit, _) => {
                return Err(CommandError::MarketReducePurpose);
            }
            (_, PositionSide::Net) => return Err(CommandError::PositionSide),
        };
        if self.side != expected_side {
            return Err(CommandError::PositionSide);
        }
        Ok(())
    }
}

impl MarketOrderCommand {
    pub fn validate(&self) -> Result<(), CommandError> {
        self.owner.validate()?;
        if self.owner.purpose != OrderPurpose::Entry {
            return Err(CommandError::MarketPurpose);
        }
        if !self.quantity.is_sign_positive() || self.quantity.is_zero() {
            return Err(CommandError::Quantity);
        }
        if self.reduce_only {
            return Err(CommandError::MarketReduceOnly);
        }
        if !matches!(self.position_side, PositionSide::Long | PositionSide::Short) {
            return Err(CommandError::PositionSide);
        }
        let expected_side = match self.position_side {
            PositionSide::Long => OrderSide::Buy,
            PositionSide::Short => OrderSide::Sell,
            PositionSide::Net => return Err(CommandError::PositionSide),
        };
        if self.side != expected_side {
            return Err(CommandError::PositionSide);
        }
        Ok(())
    }
}

impl MarketReduceCommand {
    pub fn validate(&self) -> Result<(), CommandError> {
        self.owner.validate()?;
        if [
            &self.command_id,
            &self.client_order_id,
            &self.risk_episode_id,
        ]
        .into_iter()
        .any(|identity| !valid_identifier(identity.as_str()))
        {
            return Err(CommandError::Identifier);
        }
        if self.owner.purpose != OrderPurpose::ExposureTakeProfit {
            return Err(CommandError::MarketReducePurpose);
        }
        if !self.quantity.is_sign_positive() || self.quantity.is_zero() {
            return Err(CommandError::Quantity);
        }
        let expected_side = match self.position_side {
            PositionSide::Long => OrderSide::Sell,
            PositionSide::Short => OrderSide::Buy,
            PositionSide::Net => return Err(CommandError::PositionSide),
        };
        if self.side != expected_side {
            return Err(CommandError::MarketReduceSide);
        }
        if self.position_generation == 0 {
            return Err(CommandError::PositionGeneration);
        }
        Ok(())
    }
}

fn valid_identifier(value: &str) -> bool {
    !value.is_empty()
        && value.len() <= 36
        && value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_'))
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, thiserror::Error)]
pub enum CommandError {
    #[error("command identifiers must be 1 to 36 ASCII alphanumeric, dash, or underscore bytes")]
    Identifier,
    #[error("owner identity is invalid")]
    Owner,
    #[error("command quantity must be positive")]
    Quantity,
    #[error(
        "entry commands cannot be reduce-only, while protection and reduce commands must be reduce-only"
    )]
    ReduceOnly,
    #[error("a close-all stop-market command must have protection purpose")]
    ProtectionPurpose,
    #[error("a market command must have entry purpose")]
    MarketPurpose,
    #[error("a market inventory command cannot be reduce-only")]
    MarketReduceOnly,
    #[error("a market reduction command must have exposure-take-profit purpose")]
    MarketReducePurpose,
    #[error("a market reduction side must oppose its declared Hedge leg")]
    MarketReduceSide,
    #[error("protection command position generation must be positive")]
    PositionGeneration,
    #[error("hedge protection must target the LONG or SHORT position side")]
    ProtectionPositionSide,
    #[error("hedge protection side must reduce its declared position side")]
    ProtectionSide,
    #[error("hedge order side must match a declared LONG or SHORT position side and purpose")]
    PositionSide,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reduce_only_is_bound_to_semantic_purpose() -> Result<(), Box<dyn std::error::Error>> {
        let command = OrderCommand {
            command_id: CommandId::new("command_1")?,
            client_order_id: CommandId::new("client_1")?,
            owner: OrderOwner {
                strategy_instance_id: "scalping_1".to_owned(),
                run_id: "run_1".to_owned(),
                exchange: "binance".to_owned(),
                account: "primary".to_owned(),
                symbol: "DOGE/USDT".parse()?,
                purpose: OrderPurpose::Protection,
            },
            side: OrderSide::Sell,
            position_side: PositionSide::Long,
            quantity: Decimal::ONE,
            limit_price: Price::new(Decimal::new(1, 1))?,
            reduce_only: true,
        };

        assert!(command.validate().is_ok());
        Ok(())
    }

    #[test]
    fn stop_market_close_all_has_no_quantity_or_reduce_only_escape_hatch()
    -> Result<(), Box<dyn std::error::Error>> {
        let command = StopMarketCloseAllCommand {
            command_id: CommandId::new("protect_1")?,
            client_strategy_id: CommandId::new("venue_protect_1")?,
            owner: OrderOwner {
                strategy_instance_id: "scalping_1".to_owned(),
                run_id: "run_1".to_owned(),
                exchange: "binance".to_owned(),
                account: "primary".to_owned(),
                symbol: "DOGE/USDT".parse()?,
                purpose: OrderPurpose::Protection,
            },
            side: OrderSide::Sell,
            position_side: PositionSide::Long,
            stop_price: Price::new(Decimal::new(9, 2))?,
            position_generation: 1,
        };
        assert!(command.validate().is_ok());
        Ok(())
    }

    #[test]
    fn market_inventory_command_is_opening_only_and_hedge_side_bound()
    -> Result<(), Box<dyn std::error::Error>> {
        let mut command = MarketOrderCommand {
            command_id: CommandId::new("market_1")?,
            client_order_id: CommandId::new("venue_market_1")?,
            owner: OrderOwner {
                strategy_instance_id: "hedged_grid_1".to_owned(),
                run_id: "run_1".to_owned(),
                exchange: "binance".to_owned(),
                account: "portfolio_margin_um".to_owned(),
                symbol: "SOL/USDC".parse()?,
                purpose: OrderPurpose::Entry,
            },
            position_side: PositionSide::Long,
            side: OrderSide::Buy,
            quantity: Decimal::new(15, 2),
            reduce_only: false,
        };
        command.validate()?;
        let execution = ExecutionCommand::PlaceMarket(command.clone());
        assert_eq!(
            execution.native_order_family(),
            Some(NativeOrderFamily::UmOrder)
        );
        assert_eq!(execution.native_client_id(), Some(&command.client_order_id));
        execution.validate()?;

        command.reduce_only = true;
        assert!(matches!(
            command.validate(),
            Err(CommandError::MarketReduceOnly)
        ));
        command.reduce_only = false;
        command.owner.purpose = OrderPurpose::Reduce;
        assert!(matches!(
            command.validate(),
            Err(CommandError::MarketPurpose)
        ));
        Ok(())
    }

    #[test]
    fn exposure_market_reduce_has_no_opening_or_reduce_only_escape_hatch()
    -> Result<(), Box<dyn std::error::Error>> {
        let owner = OrderOwner {
            strategy_instance_id: "hedged_grid_1".to_owned(),
            run_id: "run_1".to_owned(),
            exchange: "bitget".to_owned(),
            account: "uta_usdt".to_owned(),
            symbol: "DOGE/USDT".parse()?,
            purpose: OrderPurpose::ExposureTakeProfit,
        };
        let mut command = MarketReduceCommand {
            command_id: CommandId::new("risk_reduce_1")?,
            client_order_id: CommandId::new("venue_risk_reduce_1")?,
            owner: owner.clone(),
            position_side: PositionSide::Long,
            side: OrderSide::Sell,
            quantity: Decimal::new(180, 0),
            risk_episode_id: CommandId::new("risk_episode_1")?,
            position_generation: 9,
        };
        command.validate()?;
        let execution = ExecutionCommand::MarketReduce(command.clone());
        assert_eq!(execution.owner(), Some(&owner));
        assert_eq!(execution.native_client_id(), Some(&command.client_order_id));
        assert_eq!(
            execution.native_order_family(),
            Some(NativeOrderFamily::UmOrder)
        );

        command.side = OrderSide::Buy;
        assert_eq!(command.validate(), Err(CommandError::MarketReduceSide));
        command.side = OrderSide::Sell;
        command.owner.purpose = OrderPurpose::Entry;
        assert_eq!(command.validate(), Err(CommandError::MarketReducePurpose));
        command.owner.purpose = OrderPurpose::ExposureTakeProfit;
        command.position_generation = 0;
        assert_eq!(command.validate(), Err(CommandError::PositionGeneration));
        Ok(())
    }

    #[test]
    fn exposure_take_profit_cannot_use_legacy_limit_or_market_commands()
    -> Result<(), Box<dyn std::error::Error>> {
        let owner = OrderOwner {
            strategy_instance_id: "hedged_grid_1".to_owned(),
            run_id: "run_1".to_owned(),
            exchange: "gate".to_owned(),
            account: "usdt_futures".to_owned(),
            symbol: "DOGE/USDT".parse()?,
            purpose: OrderPurpose::ExposureTakeProfit,
        };
        let limit = OrderCommand {
            command_id: CommandId::new("wrong_limit_1")?,
            client_order_id: CommandId::new("wrong_limit_client_1")?,
            owner: owner.clone(),
            side: OrderSide::Sell,
            position_side: PositionSide::Long,
            quantity: Decimal::ONE,
            limit_price: Price::new(Decimal::ONE)?,
            reduce_only: true,
        };
        assert_eq!(limit.validate(), Err(CommandError::MarketReducePurpose));
        let market = MarketOrderCommand {
            command_id: CommandId::new("wrong_market_1")?,
            client_order_id: CommandId::new("wrong_market_client_1")?,
            owner,
            position_side: PositionSide::Long,
            side: OrderSide::Sell,
            quantity: Decimal::ONE,
            reduce_only: false,
        };
        assert_eq!(market.validate(), Err(CommandError::MarketPurpose));
        Ok(())
    }

    #[test]
    fn deserialized_market_reduce_revalidates_every_durable_identity()
    -> Result<(), Box<dyn std::error::Error>> {
        let encoded = r#"{
            "command_id":"risk_reduce_1",
            "client_order_id":"venue_risk_reduce_1",
            "owner":{
                "strategy_instance_id":"hedged_grid_1","run_id":"run_1",
                "exchange":"gate","account":"usdt_futures","symbol":"DOGE/USDT",
                "purpose":"exposure_take_profit"
            },
            "position_side":"long","side":"sell","quantity":"1",
            "risk_episode_id":"bad identity!","position_generation":1
        }"#;
        let command: MarketReduceCommand = serde_json::from_str(encoded)?;
        assert_eq!(command.validate(), Err(CommandError::Identifier));
        Ok(())
    }
}
